language: c
compiler: gcc
dist: trusty
install: make clean && make
before_script:
  - git clone --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - pip install redis ramp-packer
  - cd ..

env:
  - REDIS_MODULE_PATH=$TRAVIS_BUILD_DIR/src/module.so REDIS_PATH=$TRAVIS_BUILD_DIR/redis/src/redis-server
script: 
  - make test
  - make package

deploy:
  provider: s3
  access_key_id: "AKIAJBAS62HNYICJHEXQ"
  secret_access_key:
    secure: jxseJ9gF2y2hbFAfzDwhue7Uiz7pq7LtpRnnvMNKeLXnsdtFAuOMOHsSEMlGo0S128XpX/9Ch3olNhZIYZZz4NV5uvVxfTiDmX3RtXWAnaeC+TnZ/pUfh641/JIa7S3BJ4OEvLN9bY1etwKe80xUWPNKbMgGCBKS1NCTOxLOJ/q1G9+NRPN6lX8kL0msk7lEKFW4mYT0BQtI1U4b93XDWNq/FRnm0rM6M2a5et21uLPdBIUYhMkO6LdSQa7Su5+3itV9/LHJ46kYlY6W4hD5hVXktN+7y9NRw956DrK100SZvqhjd2WWJ8M5xbwfMbcHnn4rRgzbVZ0FmS0LkXkeD+tq/QmHrPoZFrPLOo6kHy3dkEmPuxWyX4Mc5FR9tieEi7gBckZKj4tUCmgJYpUtW1HRVIcU69Do3SfHSj9cHek5YNa6FD437FxEfK+ed51LxkNU9RuaFMUOFTfjooVnpQMVjPU4P0xU/NQqsyBUamkUDQZjXE71hzAosmrmaw+PRULM2Y7hjgRUoo6ptNk9/124WcqTfkXKE4EgEFV+eVPWx3lc3bE75XnxEIlvtrUbf6juDcO0t/C7JvbOZUhFTzxq+0WwmBSKZ3zZ5L3xrUnBUNB7OE6rVgFqiQYzw7hMIDT2uds05vJWnDWdWea7o0lTdlG2XH0hEq31tGK7Yiw=
  skip_cleanup: true
  bucket: "redisearch-builds"
  file: $(ls $TRAVIS_BUILD_DIR/src/*.zip | head -1)
  on:
    branch: package
