language: c
compiler: gcc
dist: trusty
install: make clean && make
before_script:
  - git clone --depth 1 https://github.com/antirez/redis.git
  - cd redis
  - make
  - pip install redis
  - cd ..
env:
  - REDIS_PATH=./redis/src/redis-server REDIS_MODULE_PATH=./src/module.so
script: make test