site_name: RediSearch Documentation
site_url: http://redislabsmodules.github.io/RediSearch/
theme: material
pages:
    - 'Overview': 'index.md'
    - 'Quick Start': 'Quick_Start.md'
    - 'Commands': 'Commands.md'
    - 'Stemming Support': Stemming.md