site_name: RediSearch Documentation
site_url: http://redisearch.io
canonical_url: http://redisearch.io
repo_url: https://github.com/RedisLabsModules/RediSearch
theme: material
extra:
  feature:
    tabs: true
google_analytics:
  - 'UA-89573912-1'
  - 'auto'
markdown_extensions:
  - codehilite
pages:
    - 'Home': 'index.md'
    - 'Quick Start': 'Quick_Start.md'
    - 'Commands': 'Commands.md'    
    - 'Reference':
        - 'Query Syntax': 'Query_Syntax.md'
        - 'Stemming Support': Stemming.md
        - 'Python API': python_client.md
        - 'Document Payloads': payloads.md
        - 'Extension API': Extensions.md

#google_analytics: ['UA-89573912-1', 'redisearch']