site_name: RediSearch Documentation
site_url: https://redislabsmodules.github.io/RediSearch/
canonical_url: https://redislabsmodules.github.io/RediSearch/
repo_url: https://github.com/RedisLabsModules/RediSearch
theme: material
pages:
    - 'Overview': 'index.md'
    - 'Quick Start': 'Quick_Start.md'
    - 'Commands': 'Commands.md'
    - 'Query Syntax': 'Query_Syntax.md'
    - 'Stemming Support': Stemming.md

google_analytics: ['UA-89573912-1', 'github page']