version: 2
jobs:
  build:
    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout
      - run:
          name: Build
          command: 'make -j 8'
      - run:
          name: Test
          command: make test
      # Copy the stuff needed for packaging to tmp workspace
      - run: mkdir -p /tmp/workspace
      - run: cp src/redisearch.so /tmp/workspace/
      - run: cp ramp.yml /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - redisearch.so
            - ramp.yml
  
  package_branch:
    docker:
      - image: redislabsmodules/rmbuilder:latest
    steps:
      
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Package
          command: ramp-packer -m /tmp/workspace/ramp.yml -o redisearch-oss.{os}-{architecture}.$CIRCLE_BRANCH.zip /tmp/workspace/redisearch.so

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package_branch:
          requires:
            - build
          filters:
            branches:
              only: circleci