version: 2
jobs:
  build:
    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout
      - run:
          name: Build
          command: 'make -j 8'
      - run:
          name: Test
          command: make test
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - src/redisearch.so
  
  package:
    docker:
      - image: redislabsmodules/rmbuilder:latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Package
          command: make package

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package:
          requires:
            - build
          filters:
            branches:
              only: circleci