version: 2
jobs:
  build:
    docker:
      - image: redislabsmodules/rmbuilder:latest

    steps:
      - checkout
      - run:
          name: Build
          command: 'make -j 8'
      - run:
          name: Test
          command: make test
      - run: mkdir -p /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - src/redisearch.so
  
  package:
    docker:
      - image: redislabsmodules/rmbuilder:latest
    steps:
      
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Package
          command: ramp-packer -m ramp.yml -o redisearch-oss.{os}-{architecture}.{semantic_version}.zip /tmp/workspace/redisearch.so

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package:
          requires:
            - build
          filters:
            branches:
              only: circleci